/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws ParseException, IOException {

        //Variables for later
        String exp = "";
        boolean stnd = false;
        String ifile;
        String newfl = "";

        //***Definition Stage***
        // create Options object
        Options options = new Options();
        // add options
        options.addOption(new Option("b", "batch", true, "processes the provided file rather than standard input"));
        options.addOption(new Option("h", "help", false, "prints help/usage message"));
        options.addOption(new Option("o", "output", true, "sends the output to the provided file and standard output"));

        //***Parsing Stage***
        //Create a parser
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse(options, args);

        //***Interrogation Stage***
        if (cmd.hasOption("h")) {
            System.out.println("usage: eval [OPTIONS]\n" +
                    "Evaluate simple mathematical expressions\n" +
                    "\n" +
                    "-b,--batch <file>    batch file with expressions to evaluate\n" +
                    "-h,--help            print usage message\n" +
                    "-o,--output <file>   output to this file\n" +
                    "\n" +
                    "Copyright (C) 2021 Hunter Chase");
            System.exit(0);
        }
        StdIn getExp = new StdIn(); // New Standard in object
        BatIn whole_batch = new BatIn(); // New Batch in object

        if (cmd.hasOption("b")) { // If there is a batch file
            ifile = cmd.getOptionValue("b");
            System.out.println("batch value: " + ifile);
            try{
                whole_batch.in(ifile); // Throw contents into batch object
            } catch (FileNotFoundException e) {
                System.out.println("no file found. \nexiting...");
                System.exit(0);
            }

        }
        else {
            stnd = true;
        }
            if (cmd.hasOption("o")) {
                String ofile = cmd.getOptionValue("o");
                System.out.println("Output value: " + ofile);
                newfl = cmd.getOptionValue("o");

//                try {
//                    newfl = new File(cmd.getOptionValue("o"));
//                    if (newfl.createNewFile()) {
//                        System.out.println("File created: " + newfl.getName());
//                    } else {
//                        System.out.println("File already exists.");
//                    }
//                } catch (IOException e) {
//                    System.out.println("An error occurred.");
//                    e.printStackTrace();
//                }
            }

            //Evaluations

            StdOt standard_out = new StdOt();
            BatOt batch_out = new BatOt();

            Eval maths = new Eval();
            if (cmd.hasOption("b")) {
                batch_out.create(newfl);
                while (whole_batch.check()) {
                    String next = whole_batch.out();
                    standard_out.printOut(next);
                    batch_out.printOut(next);
                    Integer out_val = maths.eval(next);
                    String result = String.valueOf(out_val);
                    standard_out.printOut(result);
                    batch_out.printOut(result);
                }
            }
            else {
                while (stnd) {
                    getExp.in();
                    if(!getExp.done()){
                        exp = getExp.out();
                        standard_out.printOut(exp);
                        Integer out_val = maths.eval(exp);
                        exp = String.valueOf(out_val);
                        standard_out.printOut(exp);
                    }
                    else{
                        stnd = false;
                    }
                }
            }
            whole_batch.close();
            batch_out.close();
        // Test Zone
        System.out.println("\nThank you\nHave a nice day");
        }
    }
