/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws ParseException, FileNotFoundException {

        //Variables for later
        String exp = "";
        Boolean stnd;

        //***Definition Stage***
        // create Options object
        Options options = new Options();
        // add options
        options.addOption(new Option("b", "batch", true, "processes the provided file rather than standard input"));
        options.addOption(new Option("h", "help", false, "prints help/usage message"));
        options.addOption(new Option("o", "output", true, "sends the output to the provided file and standard output"));

        //***Parsing Stage***
        //Create a parser
        CommandLineParser parser = new DefaultParser();
        CommandLine cmd = parser.parse(options, args);

        //***Interrogation Stage***
        if (cmd.hasOption("h")) {
            System.out.println("usage: eval [OPTIONS]\n" +
                    "Evaluate simple mathematical expressions\n" +
                    "\n" +
                    "-b,--batch <file>    batch file with expressions to evaluate\n" +
                    "-h,--help            print usage message\n" +
                    "-o,--output <file>   output to this file\n" +
                    "\n" +
                    "Copyright (C) 2021 Hunter Chase");
            System.exit(0);
        }
        StdIn getExp = new StdIn(); // New Standard in object
        BatIn whole_batch = new BatIn(); // New Batch in object
        if (cmd.hasOption("b")) { // If there is a batch file
            String ifile = cmd.getOptionValue("b");
            System.out.println("batch value: " + ifile);
            try{
                whole_batch.in(ifile); // Throw contents into batch object
            } catch (FileNotFoundException e) {
                System.out.println("no file found. \nexiting...");
                System.exit(0);
            }

        }
        else {
            getExp.in();
            exp = getExp.out();
        }
            if (cmd.hasOption("o")) {
                String ofile = cmd.getOptionValue("o");
                System.out.println("Output value: " + ofile);
            }

            //Evaluations
            Eval maths = new Eval();
            if (cmd.hasOption("b")) {
                while (whole_batch.check()) {
                    String next = whole_batch.out();
                    System.out.println(next);
                    Integer out_val = maths.eval(next);
                    System.out.println(out_val);
                }
            }
            else {
                while (!getExp.done()) {
                    Integer out_val = maths.eval(exp);
                    System.out.println(out_val);
                    getExp.in();
                    exp = getExp.out();
                }
            }
        // Test Zone
        System.out.println("\nThank you\nHave a nice day");
        }
    }
